## Dataset Exploration Summary

### General

- Contains 2643 listings and 59 columns after initial pass
- Investigated missing values, feature distributions, and potential data leakage to determine what to retain

### Missing Data Analysis

In [2]:
import pandas as pd
from src.utils.paths import PROCESSED_DATA_DIR

In [3]:
df = pd.read_csv(PROCESSED_DATA_DIR / "listings_clean.csv")

In [5]:
df.head()

,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2011-01-29,Singapore,within a few hours,100%,100%,False,Tampines,5,10,"['email', 'phone']",...,4.43,4.17,4.04,NaN,False,5,0,5,0,0.14
1,2011-01-29,Singapore,within a few hours,100%,100%,False,Tampines,5,10,"['email', 'phone']",...,4.64,4.50,4.36,NaN,False,5,0,5,0,0.26
2,2011-12-20,Singapore,within a few hours,100%,100%,False,Central Area,7,8,"['email', 'phone']",...,4.66,4.52,4.39,NaN,False,7,1,6,0,0.79
3,2011-01-29,Singapore,within a few hours,100%,100%,False,Tampines,5,10,"['email', 'phone']",...,4.58,4.66,4.44,NaN,True,5,0,5,0,0.36
4,2011-12-20,Singapore,within a few hours,100%,100%,False,Central Area,7,8,"['email', 'phone']",...,4.76,4.64,4.55,NaN,False,7,1,6,0,0.55

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2643 entries, 0 to 2642
Data columns (total 59 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   host_since                                    2643 non-null   str
 1   host_location                                 1705 non-null   str
 2   host_response_time                            2269 non-null   str
 3   host_response_rate                            2269 non-null   str
 4   host_acceptance_rate                          2188 non-null   str
 5   host_is_superhost                             2643 non-null   bool
 6   host_neighbourhood                            2557 non-null   str
 7   host_listings_count                           2643 non-null   int64
 8   host_total_listings_count                     2643 non-null   int64
 9   host_verifications                            2643 non-null   str
 10  host_has_profile_pic                          2643 non-null   bool
 11  host_identity_verified                        2643 non-null   bool
 12  neighbourhood                                 1372 non-null   str
 13  neighbourhood_cleansed                        2643 non-null   str
 14  neighbourhood_group_cleansed                  2643 non-null   str
 15  latitude                                      2643 non-null   float64
 16  longitude                                     2643 non-null   float64
 17  property_type                                 2643 non-null   str
 18  room_type                                     2643 non-null   str
 19  accommodates                                  2643 non-null   int64
 20  bathrooms                                     2641 non-null   float64
 21  bathrooms_text                                2639 non-null   str
 22  bedrooms                                      2632 non-null   float64
 23  beds                                          2620 non-null   float64
 24  price                                         2643 non-null   float64
 25  minimum_nights                                2643 non-null   int64
 26  maximum_nights                                2643 non-null   int64
 27  minimum_minimum_nights                        2643 non-null   float64
 28  maximum_minimum_nights                        2643 non-null   float64
 29  minimum_maximum_nights                        2643 non-null   float64
 30  maximum_maximum_nights                        2643 non-null   float64
 31  minimum_nights_avg_ntm                        2643 non-null   float64
 32  maximum_nights_avg_ntm                        2643 non-null   float64
 33  has_availability                              2643 non-null   bool
 34  availability_30                               2643 non-null   int64
 35  availability_60                               2643 non-null   int64
 36  availability_90                               2643 non-null   int64
 37  availability_365                              2643 non-null   int64
 38  number_of_reviews                             2643 non-null   int64
 39  number_of_reviews_ltm                         2643 non-null   int64
 40  number_of_reviews_l30d                        2643 non-null   int64
 41  availability_eoy                              2643 non-null   int64
 42  number_of_reviews_ly                          2643 non-null   int64
 43  first_review                                  1359 non-null   str
 44  last_review                                   1359 non-null   str
 45  review_scores_rating                          1359 non-null   float64
 46  review_scores_accuracy                        1359 non-null   float64
 47  review_scores_cleanliness                     1359 non-null   float64
 48  review_scores_checkin                         1359 non-null   float64
 49  review_scores_communication                   1359 non-null   float64
 50  review_scores_location                        1358 non-null   float64
 51  review_scores_value                           1358 non-null   float64
 52  license                                       1564 non-null   str
 53  instant_bookable                              2643 non-null   bool
 54  calculated_host_listings_count                2643 non-null   int64
 55  calculated_host_listings_count_entire_homes   2643 non-null   int64
 56  calculated_host_listings_count_private_rooms  2643 non-null   int64
 57  calculated_host_listings_count_shared_rooms   2643 non-null   int64
 58  reviews_per_month                             1359 non-null   float64
dtypes: bool(5), float64(20), int64(18), str(16)
memory usage: 1.1 MB

In [7]:
df.isna().sum().sort_values(ascending=False)

review_scores_value                             1285
review_scores_location                          1285
last_review                                     1284
review_scores_accuracy                          1284
review_scores_cleanliness                       1284
review_scores_rating                            1284
first_review                                    1284
review_scores_checkin                           1284
reviews_per_month                               1284
review_scores_communication                     1284
neighbourhood                                   1271
license                                         1079
host_location                                    938
host_acceptance_rate                             455
host_response_rate                               374
host_response_time                               374
host_neighbourhood                                86
beds                                              23
bedrooms                                          11
bathrooms_text                                     4
bathrooms                                          2
host_has_profile_pic                               0
host_listings_count                                0
host_is_superhost                                  0
host_verifications                                 0
host_total_listings_count                          0
host_since                                         0
maximum_nights                                     0
minimum_nights                                     0
price                                              0
accommodates                                       0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
neighbourhood_group_cleansed                       0
neighbourhood_cleansed                             0
host_identity_verified                             0
minimum_minimum_nights                             0
minimum_nights_avg_ntm                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
number_of_reviews_ly                               0
availability_eoy                                   0
number_of_reviews_l30d                             0
number_of_reviews_ltm                              0
number_of_reviews                                  0
availability_365                                   0
availability_90                                    0
availability_60                                    0
availability_30                                    0
has_availability                                   0
maximum_nights_avg_ntm                             0
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

In [8]:
df["host_location"].value_counts().head(20)

host_location
Singapore                    1451
Uttar Pradesh, India          132
Paris, France                  49
France                         20
Amsterdam, Netherlands         13
Jakarta, Indonesia              7
Bangkok, Thailand               7
Hong Kong                       4
New York, NY                    3
San Francisco, CA               3
Malaysia                        3
Seattle, WA                     2
London, United Kingdom          2
Barcelona, Spain                1
Munich, Germany                 1
Barbastro, Spain                1
Worcester, United Kingdom       1
Berlin, Germany                 1
Phuket, Thailand                1
Columbus, OH                    1
Name: count, dtype: int64

In [11]:
(
    (df["number_of_reviews"] == 0)
    ==
    (df["review_scores_rating"].isna())
).all()

np.True_

In [ ]:
df["license"].nunique()

134

In [16]:
df["license"].head(20)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10    S0399
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
Name: license, dtype: str

In [17]:
df["license"].value_counts().head(20)

license
Authorised Serviced Apartment    862
Exempt                           242
S0399                             53
S0430                             15
S0483                             12
S0301                             10
S0269                              9
M0073                              9
S0408                              9
S0001                              9
S0595                              9
S0457                              8
S0543                              8
S0452                              8
S0485                              8
S0464                              7
S0282                              7
S0554                              7
S0506                              7
M1234                              6
Name: count, dtype: int64

In [18]:
df["host_response_time"].value_counts(dropna=False)

host_response_time
within an hour        1174
within a day           521
NaN                    374
a few days or more     334
within a few hours     240
Name: count, dtype: int64

In [19]:
df["host_acceptance_rate"].value_counts(dropna=False)

host_acceptance_rate
100%    676
NaN     455
12%     215
68%     162
99%     157
98%     115
11%     114
86%     102
67%     101
0%       89
50%      74
89%      53
22%      43
91%      28
35%      23
92%      22
88%      21
81%      20
90%      16
46%      16
83%      16
96%      15
32%      13
97%      13
60%      11
75%       9
33%       7
80%       7
40%       7
25%       7
70%       7
78%       6
57%       4
95%       4
77%       3
61%       2
74%       2
73%       2
94%       1
20%       1
85%       1
82%       1
21%       1
18%       1
Name: count, dtype: int64

In [20]:
df["host_verifications"].value_counts().head(20)

host_verifications
['email', 'phone']                  2165
['email', 'phone', 'work_email']     263
['phone']                            212
['phone', 'work_email']                2
['email', 'work_email']                1
Name: count, dtype: int64

In [21]:
df["host_neighbourhood"].value_counts().head(20)

host_neighbourhood
River Valley          297
Kallang               229
Central               216
Queenstown            198
Bukit Merah           173
Crows Nest            114
Katong                110
Geylang               107
Bugis/Kampong Glam     98
Chinatown              95
Clementi               72
Rochor                 60
Outram                 60
Central Area           56
Bedok                  52
Novena                 47
Marine Parade          47
Downtown Core          42
Jurong West            34
Bukit Timah            32
Name: count, dtype: int64

In [22]:
df["host_response_rate"].value_counts(dropna=False)

host_response_rate
100%    1012
NaN      374
74%      215
0%       131
33%      118
50%      109
98%      102
89%       84
97%       79
60%       71
99%       66
25%       44
80%       38
94%       25
88%       22
93%       18
43%       17
69%       13
90%       13
67%       11
75%       10
10%       10
83%       10
92%        9
91%        7
96%        6
24%        5
30%        4
78%        3
70%        3
56%        2
95%        2
85%        2
21%        2
29%        1
86%        1
40%        1
57%        1
71%        1
20%        1
Name: count, dtype: int64

In [25]:
df.select_dtypes(include=["number"]).describe()

,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000,2641.000000,2632.000000,2620.000000,2643.000000,2643.000000,...,1359.000000,1359.000000,1359.000000,1358.000000,1358.000000,2643.000000,2643.000000,2643.000000,2643.000000,1359.000000
mean,89.415815,151.760878,1.307986,103.842736,2.762391,1.439228,1.251140,1.621374,345.269769,56.642073,...,4.562509,4.761030,4.746939,4.721200,4.472658,52.698449,39.317442,13.030647,0.169126,0.554194
std,143.983287,254.786701,0.028210,0.042555,1.744764,0.937739,0.816263,1.311156,842.116630,50.455891,...,0.581865,0.430146,0.486846,0.424736,0.598150,63.016666,65.270690,21.460935,1.218921,1.551775
min,1.000000,1.000000,1.222720,103.689840,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,5.000000,7.000000,1.292056,103.833895,2.000000,1.000000,1.000000,1.000000,94.000000,4.000000,...,4.370000,4.670000,4.670000,4.620000,4.250000,4.000000,0.000000,1.000000,0.000000,0.040000
50%,35.000000,49.000000,1.302530,103.842530,2.000000,1.000000,1.000000,1.000000,221.000000,92.000000,...,4.750000,4.930000,4.940000,4.880000,4.615000,29.000000,2.000000,3.000000,0.000000,0.150000
75%,77.000000,144.000000,1.316330,103.858736,4.000000,2.000000,1.000000,2.000000,359.000000,92.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,73.000000,48.000000,15.000000,0.000000,0.500000
max,517.000000,885.000000,1.457802,103.985176,16.000000,13.000000,8.000000,22.000000,13000.000000,730.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,219.000000,219.000000,89.000000,13.000000,26.070000